spring:
  application:
    name: websocket-gateway

server:
  port: 8081
  websocket-port: 8000


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId:-},%X{spanId:-}] %-5level %logger{36} - %msg%n"